
import { RecoveryStage, Recipe, MedicalTip } from './types';

export const RECIPES: Recipe[] = [
  // --- 초기 (0-1개월) : 미음 및 아주 부드러운 유동식 (15개) ---
  { id: 'e1', title: '고단백 쌀미음', stage: RecoveryStage.EARLY, ingredients: ['쌀 1/2컵', '물 6컵', '두부 30g'], steps: ['쌀을 푹 퍼지게 끓인 후 체에 겁니다.', '두부를 으깨어 섞습니다.'], tip: '수분 보충이 최우선!', image: '' },
  { id: 'e2', title: '단호박 미음', stage: RecoveryStage.EARLY, ingredients: ['단호박 100g', '쌀가루 2큰술'], steps: ['호박을 쪄서 껍질을 제거합니다.', '쌀가루와 함께 곱게 갑니다.'], tip: '베타카로틴이 풍부해요.', image: '' },
  { id: 'e3', title: '감자 수프 (우유 제외)', stage: RecoveryStage.EARLY, ingredients: ['감자 1개', '채수 1컵'], steps: ['감자를 삶아 곱게 으깹니다.', '채수와 함께 뭉근히 끓입니다.'], tip: '우유 대신 채수를 쓰세요.', image: '' },
  { id: 'e4', title: '브로콜리 미음', stage: RecoveryStage.EARLY, ingredients: ['브로콜리 송이 2개', '쌀미음 1컵'], steps: ['브로콜리를 데쳐 꽃부분만 갑니다.', '미음과 섞어 한 번 더 끓입니다.'], tip: '비타민 C 보충용!', image: '' },
  { id: 'e5', title: '대구살 고운 죽', stage: RecoveryStage.EARLY, ingredients: ['흰살생선 30g', '불린 쌀 1/4컵'], steps: ['생선을 쪄서 가시를 완벽히 제거합니다.', '쌀과 함께 푹 끓여 체에 겁니다.'], tip: '최고의 단백질 공급원.', image: '' },
  { id: 'e6', title: '배 미음', stage: RecoveryStage.EARLY, ingredients: ['배 1/4개', '쌀미음 1컵'], steps: ['배 껍질을 벗기고 강판에 갑니다.', '즙만 미음에 섞어 드세요.'], tip: '천연 단맛으로 기운내기.', image: '' },
  { id: 'e7', title: '검은콩 곱게 간 즙', stage: RecoveryStage.EARLY, ingredients: ['검은콩 20g', '물 1컵'], steps: ['콩을 푹 삶아 껍질을 벗깁니다.', '물과 함께 곱게 갈아 체에 겁니다.'], tip: '식물성 단백질 왕.', image: '' },
  { id: 'e8', title: '당근 쌀미음', stage: RecoveryStage.EARLY, ingredients: ['당근 20g', '쌀미음 1컵'], steps: ['당근을 푹 익혀 곱게 갑니다.', '미음에 섞어 색을 냅니다.'], tip: '눈 건강과 면역력.', image: '' },
  { id: 'e9', title: '애호박 미음', stage: RecoveryStage.EARLY, ingredients: ['애호박 30g', '쌀미음 1컵'], steps: ['호박 속살만 삶아 갑니다.', '미음과 섞어 가볍게 끓입니다.'], tip: '소화가 아주 잘 돼요.', image: '' },
  { id: 'e10', title: '쇠고기 맑은 육수', stage: RecoveryStage.EARLY, ingredients: ['안심 50g', '물 3컵'], steps: ['고기 핏물을 빼고 푹 삶습니다.', '기름기를 완전히 걷어낸 육수만 드세요.'], tip: '철분 보충의 시작.', image: '' },
  { id: 'e11', title: '사과 익힌 즙', stage: RecoveryStage.EARLY, ingredients: ['사과 1/4개'], steps: ['사과를 쪄서 부드럽게 만듭니다.', '강판에 갈아 즙을 냅니다.'], tip: '위벽 자극을 줄여요.', image: '' },
  { id: 'e12', title: '순두부 맑은 탕 (건더기 없이)', stage: RecoveryStage.EARLY, ingredients: ['순두부 50g', '다시마 육수'], steps: ['육수에 순두부를 넣고 끓입니다.', '체에 걸러 맑은 국물 위주로 섭취.'], tip: '부담 없는 단백질.', image: '' },
  { id: 'e13', title: '연근 미음', stage: RecoveryStage.EARLY, ingredients: ['연근 20g', '쌀미음'], steps: ['연근 껍질을 벗기고 갈아 즙을 냅니다.', '미음과 섞어 살짝 끓입니다.'], tip: '위 점막 보호 도움.', image: '' },
  { id: 'e14', title: '양배추 미음', stage: RecoveryStage.EARLY, ingredients: ['양배추 잎 2장', '쌀미음'], steps: ['양배추 심지를 제거하고 삶습니다.', '곱게 갈아 미음에 섞습니다.'], tip: '비타민 U의 힘!', image: '' },
  { id: 'e15', title: '청포묵 미음', stage: RecoveryStage.EARLY, ingredients: ['청포묵 30g', '멸치육수'], steps: ['묵을 데쳐서 아주 곱게 갈아줍니다.', '육수와 섞어 미음 형태로 드세요.'], tip: '깔끔한 맛.', image: '' },

  // --- 중기 (1-6개월) : 진죽 및 부드러운 반찬 (20개) ---
  { id: 'm1', title: '대구살 애호박 찜', stage: RecoveryStage.MIDDLE, ingredients: ['대구살 80g', '애호박 1/4개'], steps: ['호박은 껍질 벗겨 찌고 대구살도 찝니다.', '둘을 잘게 으깨어 섞습니다.'], tip: '30번 씹는 연습!', image: '' },
  { id: 'm2', title: '닭안심 감자죽', stage: RecoveryStage.MIDDLE, ingredients: ['닭안심 50g', '감자 1개', '쌀죽'], steps: ['닭안심은 삶아 결대로 찢어 다집니다.', '죽과 감자를 넣고 함께 끓입니다.'], tip: '담백한 고단백식.', image: '' },
  { id: 'm3', title: '연두부 계란찜', stage: RecoveryStage.MIDDLE, ingredients: ['연두부 1팩', '계란 1개'], steps: ['연두부와 계란을 잘 섞어 체에 겁니다.', '중불에서 10분간 쪄냅니다.'], tip: '푸딩처럼 부드럽게.', image: '' },
  { id: 'm4', title: '소고기 야채 진죽', stage: RecoveryStage.MIDDLE, ingredients: ['다진 소고기 40g', '당근/양파 조금'], steps: ['채소와 고기를 아주 잘게 다집니다.', '참기름 살짝 둘러 볶은 후 죽을 끓입니다.'], tip: '기름기는 최소화.', image: '' },
  { id: 'm5', title: '임면수 구이 (살만)', stage: RecoveryStage.MIDDLE, ingredients: ['임면수 1토막'], steps: ['생선을 노릇하게 구워 껍질을 제거합니다.', '가운데 부드러운 살만 발라 드세요.'], tip: '짠맛은 줄여주세요.', image: '' },
  { id: 'm6', title: '새우살 브로콜리 볶음', stage: RecoveryStage.MIDDLE, ingredients: ['칵테일새우 5마리', '브로콜리 조금'], steps: ['새우를 다지고 브로콜리는 데쳐 다집니다.', '약한 불에 살짝 볶습니다.'], tip: '잘게 다지는 게 핵심.', image: '' },
  { id: 'm7', title: '흰살생선 야채 조림', stage: RecoveryStage.MIDDLE, ingredients: ['동태살 100g', '무 1조각'], steps: ['무를 얇게 썰어 바닥에 깔고 생선을 올립니다.', '연한 간장 양념으로 푹 조립니다.'], tip: '무가 소화를 도와요.', image: '' },
  { id: 'm8', title: '가지 나물 찜', stage: RecoveryStage.MIDDLE, ingredients: ['가지 1개'], steps: ['가지를 쪄서 껍질을 벗깁니다.', '속살만 부드럽게 무쳐 드세요.'], tip: '부드러운 식감이 일품.', image: '' },
  { id: 'm9', title: '두부 버섯 들깨탕', stage: RecoveryStage.MIDDLE, ingredients: ['두부 1/2모', '팽이버섯 조금', '들깨가루 1큰술'], steps: ['멸치 육수에 재료를 넣고 끓입니다.', '들깨가루로 고소함을 더합니다.'], tip: '기력 회복에 좋아요.', image: '' },
  { id: 'm10', title: '닭가슴살 샐러드 (익힌 채소)', stage: RecoveryStage.MIDDLE, ingredients: ['닭가슴살 50g', '익힌 당근/브로콜리'], steps: ['닭은 삶아 찢고 채소는 푹 익힙니다.', '드레싱 없이 올리브유만 살짝.'], tip: '생채소는 아직 주의!', image: '' },
  { id: 'm11', title: '바나나 으깸', stage: RecoveryStage.MIDDLE, ingredients: ['바나나 1/2개'], steps: ['잘 익은 바나나를 포크로 으깹니다.'], tip: '간식으로 최고!', image: '' },
  { id: 'm12', title: '사과 익힘 디저트', stage: RecoveryStage.MIDDLE, ingredients: ['사과 1/2개'], steps: ['사과를 얇게 썰어 물 조금 넣고 졸입니다.', '시나몬 가루를 살짝 뿌려도 좋아요.'], tip: '단순 당분은 조심!', image: '' },
  { id: 'm13', title: '고구마 메시', stage: RecoveryStage.MIDDLE, ingredients: ['찐고구마 1개'], steps: ['고구마를 쪄서 껍질 제거 후 으깹니다.', '퍽퍽하면 물을 조금 섞으세요.'], tip: '섬유질 섭취의 시작.', image: '' },
  { id: 'm14', title: '전복 잘게 다진 죽', stage: RecoveryStage.MIDDLE, ingredients: ['전복 1마리', '쌀죽'], steps: ['전복을 아주 잘게 다집니다.', '참기름에 볶아 죽을 쑵니다.'], tip: '보양식의 대명사.', image: '' },
  { id: 'm15', title: '굴 맑은 국 (건더기 조금)', stage: RecoveryStage.MIDDLE, ingredients: ['생굴 3개', '부추 조금'], steps: ['무 육수에 굴을 넣고 시원하게 끓입니다.', '부추는 아주 잘게 썹니다.'], tip: '아연이 풍부해요.', image: '' },
  { id: 'm16', title: '대구전 (부드럽게)', stage: RecoveryStage.MIDDLE, ingredients: ['대구살', '계란'], steps: ['생선살에 밀가루/계란옷을 입힙니다.', '기름을 적게 두르고 부드럽게 굽습니다.'], tip: '기름기는 키친타월로 제거.', image: '' },
  { id: 'm17', title: '청포묵 무침', stage: RecoveryStage.MIDDLE, ingredients: ['청포묵 100g', '김가루조금'], steps: ['묵을 데쳐 채 썹니다.', '간장/참기름으로 약하게 간합니다.'], tip: '탱글한 식감.', image: '' },
  { id: 'm18', title: '감자 조림', stage: RecoveryStage.MIDDLE, ingredients: ['감자 2개'], steps: ['감자를 한입 크기로 썰어 푹 조립니다.', '입안에서 으깨질 정도로 익히세요.'], tip: '든든한 반찬.', image: '' },
  { id: 'm19', title: '두부 조림 (안 맵게)', stage: RecoveryStage.MIDDLE, ingredients: ['두부 1/2모'], steps: ['간장 양념으로 짜지 않게 조립니다.', '고춧가루는 넣지 마세요.'], tip: '자극은 금물!', image: '' },
  { id: 'm20', title: '소고기 안심 찜', stage: RecoveryStage.MIDDLE, ingredients: ['안심 60g', '양파'], steps: ['고기를 아주 얇게 썰어 채소와 함께 찝니다.', '고기가 질기지 않게 주의하세요.'], tip: '소화하기 쉽게 조리.', image: '' },

  // --- 후기 (6-12개월) : 일반식 적응기 (15개) ---
  { id: 'l1', title: '소고기 버섯 맑은 조림', stage: RecoveryStage.LATE, ingredients: ['우둔살 80g', '표고버섯 2개'], steps: ['고기와 버섯을 얇게 썹니다.', '자극적이지 않은 간장 베이스로 졸입니다.'], tip: '단백질 폭탄!', image: '' },
  { id: 'l2', title: '삼치 구이', stage: RecoveryStage.LATE, ingredients: ['삼치 1토막'], steps: ['생선을 노릇하게 구워 껍질을 제거합니다.', '껍질까지 조금씩 시도해 보세요.'], tip: '오메가3 듬뿍.', image: '' },
  { id: 'l3', title: '계란 볶음밥 (진밥)', stage: RecoveryStage.LATE, ingredients: ['진밥 1공기', '계란 1개', '파조금'], steps: ['밥을 평소보다 질게 짓습니다.', '스크램블 에그와 함께 볶아냅니다.'], tip: '꼭꼭 씹어 먹기!', image: '' },
  { id: 'l4', title: '버섯 잡채 (잘게 썬)', stage: RecoveryStage.LATE, ingredients: ['당면 50g', '각종 버섯'], steps: ['당면을 푹 삶아 가위로 잘게 자릅니다.', '버섯과 함께 볶습니다.'], tip: '당면은 소화가 늦으니 주의.', image: '' },
  { id: 'l5', title: '연어 스테이크 (부드러운 부위)', stage: RecoveryStage.LATE, ingredients: ['연어 100g'], steps: ['연어를 팬에 부드럽게 익힙니다.', '레몬즙을 살짝 뿌려 드세요.'], tip: '양질의 지방 섭취.', image: '' },
  { id: 'l6', title: '닭다리살 간장 조림', stage: RecoveryStage.LATE, ingredients: ['닭다리살 100g'], steps: ['기름기를 제거한 닭다리살을 졸입니다.', '가슴살보다 부드러워 소화에 좋아요.'], tip: '껍질은 떼고 드세요.', image: '' },
  { id: 'l7', title: '멸치 볶음 (부드러운 것)', stage: RecoveryStage.LATE, ingredients: ['세멸치 30g'], steps: ['아주 작은 멸치를 부드럽게 볶습니다.', '견과류 가루를 뿌려도 좋습니다.'], tip: '칼슘 보충용.', image: '' },
  { id: 'l8', title: '시금치 나물 (푹 익힌)', stage: RecoveryStage.LATE, ingredients: ['시금치 1단'], steps: ['시금치를 푹 데쳐서 줄기는 잘라냅니다.', '잎 위주로 부드럽게 무칩니다.'], tip: '철분과 비타민.', image: '' },
  { id: 'l9', title: '불고기 (얇은 것)', stage: RecoveryStage.LATE, ingredients: ['샤브샤브용 고기'], steps: ['아주 얇은 고기를 양념해 볶습니다.', '질긴 부분은 가위로 다집니다.'], tip: '철분 보충 최고.', image: '' },
  { id: 'l10', title: '애호박전', stage: RecoveryStage.LATE, ingredients: ['애호박 1/2개'], steps: ['호박을 얇게 썰어 부칩니다.', '기름기를 꽉 짜서 드세요.'], tip: '익힌 채소가 정답.', image: '' },
  { id: 'l11', title: '콩나물국 (건더기 위주)', stage: RecoveryStage.LATE, ingredients: ['콩나물 한 줌'], steps: ['맑게 끓여서 콩나물 머리는 떼고 드세요.', '국물은 최소한으로만.'], tip: '숙취 아님, 영양 보충!', image: '' },
  { id: 'l12', title: '마 가루 주스', stage: RecoveryStage.LATE, ingredients: ['마 가루 1큰술', '물 1컵'], steps: ['마 가루를 물에 타서 저어 드세요.', '위벽 보호에 아주 좋습니다.'], tip: '끈적임이 보약.', image: '' },
  { id: 'l13', title: '미역국 (고기 듬뿍)', stage: RecoveryStage.LATE, ingredients: ['마른 미역', '소고기 안심'], steps: ['미역을 충분히 불려 부드럽게 끓입니다.', '고기를 많이 넣어 단백질 보충.'], tip: '미역은 잘게 썰어주세요.', image: '' },
  { id: 'l14', title: '숙주 나물 무침', stage: RecoveryStage.LATE, ingredients: ['숙주 나물'], steps: ['숙주를 데쳐 물기를 꽉 짭니다.', '자극 없이 무쳐 드세요.'], tip: '아삭함보다는 부드러움.', image: '' },
  { id: 'l15', title: '가자미 구이', stage: RecoveryStage.LATE, ingredients: ['가자미 1마리'], steps: ['비린내 없는 가자미를 굽습니다.', '부드러운 살코기를 즐기세요.'], tip: '소화 부담 제로.', image: '' },
];

export const MEDICAL_TIPS: MedicalTip[] = [
  { title: '덤핑 증후군 예방', content: '식사 중이나 직후에는 물을 마시지 마세요. 음식물이 소장으로 너무 빨리 내려가는 것을 방지합니다.', category: '주의사항' },
  { title: '30-30 법칙', content: '한 입에 30번 씹고, 식사 시간은 최소 30분을 유지하세요. 위가 없거나 작아진 상태에서 소화를 돕는 필수 수칙입니다.', category: '생활습관' },
  { title: '단백질 우선 섭취', content: '상처 회복을 위해 끼니마다 계란, 두부, 생선 등 양질의 단백질을 가장 먼저 드세요.', category: '영양' },
  { title: '소량 다회 식사', content: '하루에 6~8회로 나누어 조금씩 자주 먹는 것이 위장의 부담을 줄이는 가장 좋은 방법입니다.', category: '영양' },
  { title: '철분 보충', content: '위 절제 후에는 철분 흡수율이 떨어질 수 있습니다. 붉은 살코기와 잎채소를 챙겨 드세요.', category: '영양' },
  { title: '비타민 B12 체크', content: '위 절제 환자는 비타민 B12 흡수가 어려울 수 있으니 정기적인 검진과 필요시 주사 처방이 필요합니다.', category: '주의사항' },
  { title: '과도한 당분 금지', content: '고농도의 설탕물이나 시럽은 덤핑 증후군을 유발하는 주범입니다. 과일 주스도 주의하세요.', category: '주의사항' },
  { title: '식후 가벼운 산책', content: '식후 바로 눕지 말고 15~30분 정도 천천히 걷는 것이 소화와 역류 방지에 도움됩니다.', category: '생활습관' },
  { title: '자극적인 양념 피하기', content: '고춧가루, 후추, 겨자 등 매운 양념은 위 점막을 자극해 염증을 유발할 수 있습니다.', category: '주의사항' },
  { title: '음식 온도 조절', content: '너무 뜨겁거나 차가운 음식은 위장에 경련을 일으킬 수 있습니다. 미지근한 온도가 가장 좋아요.', category: '생활습관' },
  { title: '금연과 금주', content: '수술 후 1년은 회복의 골든타임입니다. 술과 담배는 점막 회복을 방해하고 암 재발 위험을 높입니다.', category: '주의사항' },
  { title: '체중 관리', content: '급격한 체중 감소는 근육 소실로 이어집니다. 조금씩이라도 칼로리를 충분히 섭취해야 합니다.', category: '영양' },
  { title: '섬유질 조절', content: '초기에는 거친 섬유질(말린 나물, 생채소)보다는 익힌 채소 위주로 부드럽게 섭취하세요.', category: '영양' },
  { title: '칼슘과 골다공증', content: '위 수술 후 칼슘 흡수가 저하될 수 있으니 멸치, 뱅어포 등을 꾸준히 섭취하세요.', category: '영양' },
  { title: '충분한 수분', content: '식간(식사 1시간 전/후)에 충분한 물을 마셔 탈수를 예방하세요.', category: '영양' },
  { title: '껌 씹기 금지', content: '껌을 씹으면 공기가 함께 들어가 복부 팽만감을 유발할 수 있습니다.', category: '주의사항' },
  { title: '식후 자세', content: '식후에는 상체를 15~30도 정도 높인 자세로 쉬는 것이 역류 방지에 좋습니다.', category: '생활습관' },
  { title: '단순 당질 제한', content: '꿀, 설탕, 잼 같은 단순 당질은 소장에서 수분을 급격히 끌어당겨 덤핑 증후군을 일으킵니다.', category: '주의사항' },
  { title: '빈혈 예방', content: '어지러움이 느껴진다면 철분 결핍성 빈혈일 수 있으니 혈액 검사를 받아보세요.', category: '주의사항' },
  { title: '입맛 돋우기', content: '입맛이 없을 땐 약간의 신맛(레몬즙 등)을 활용해 타액 분비를 유도해 보세요.', category: '생활습관' },
  { title: '천천히 먹기', content: '빨리 먹으면 공기가 함께 넘어가 가스가 차고 통증이 생길 수 있습니다.', category: '생활습관' },
  { title: '간식의 활용', content: '식사량이 적을 땐 우유(유당불내증 주의), 두유, 삶은 감자 등을 간식으로 활용하세요.', category: '영양' },
  { title: '가공식품 멀리하기', content: '햄, 소시지 등 가공식품에 든 보존제는 위장에 좋지 않은 영향을 줍니다.', category: '주의사항' },
  { title: '식사 일기 기록', content: '어떤 음식을 먹었을 때 불편했는지 기록해두면 나만의 안전한 식단을 만들 수 있습니다.', category: '생활습관' },
  { title: '스트레스 관리', content: '위장은 감정에 민감합니다. 편안한 환경에서 즐겁게 식사하는 것이 중요합니다.', category: '생활습관' },
  { title: '탄산음료 주의', content: '탄산음료의 가스는 위 팽창을 유발해 통증과 불편함을 줄 수 있습니다.', category: '주의사항' },
  { title: '규칙적인 식사', content: '정해진 시간에 식사하는 습관은 위장의 리듬을 되찾는 데 큰 도움이 됩니다.', category: '생활습관' },
  { title: '기름진 음식 제한', content: '튀김 등 기름진 음식은 소화 시간을 늦추고 설사를 유발할 수 있습니다.', category: '영양' },
  { title: '근육 강화', content: '걷기 운동과 병행하여 단백질을 섭취하면 기초 대사량을 유지할 수 있습니다.', category: '생활습관' },
  { title: '정기 검진의 중요성', content: '수술 후 정기적인 내시경과 혈액 검사는 재발 방지의 핵심입니다.', category: '주의사항' },
  { title: '나트륨 줄이기', content: '짠 음식은 위 점막을 손상시킵니다. 싱겁게 먹는 습관을 들이세요.', category: '영양' },
];

export const RANDOM_MESSAGES = [
  "고객님 운동하셨어요^^? 살살 걸어보시죠!",
  "고객님 덕질은 잘 하고 계시죠?^^ 최애 생각하며 기운내세요!",
  "오늘 단백질 챙겨 드셨나요? 꼼꼼히 체크하세요!",
  "꼭꼭 씹어 드시는 거 잊지 마세요! 위장님이 힘들어해요~",
  "오늘도 당신의 회복을 응원합니다! 힙하게 먹고 힙하게 낫자!"
];
